services:

  #Service 1 springboot user management service:
  user-service:
    image: "logeswaranu/user:v1"
    container_name: "user-service"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - ecommerce-network
 
# Network for the services
networks:
  ecommerce-network:
    driver: bridge